### ISSUE TITLE
workflow.md 파일에서 구분선이 일관성이 없는 것 같습니다.

### ISSUE THREAD

**Issue by rasauq1122** [Ioftware/IOFT_FLOW#10]
구분선을 모두 제거 하거나,  
아니면 모든 소제목 다음에 구분선이 오도록 해야할 것 같습니다.

**Comment by herjn** [comment]
네 팀원 파트, pull request 부분에서 구분선이 빠졌네요 
그 파트 맡았던 분 들이 고쳐주시면 될 것 같아요 ~
이따 확인할게요 :)

**Comment by rasauq1122** [comment]
어려운 일은 아니니 제가 빠진 부분에 구분선을 추가하여 PR 보내도록 하겠습니다!
