### ISSUE TITLE
workflow.md 파일에 '가정' 부분이 두 번 나옵니다.

### ISSUE THREAD

**Issue by rasauq1122** [Ioftware/IOFT_FLOW#8]
workflow.md 파일에 11번 - 20번 라인에 '가정' 부분이 두 번 나옵니다.  
아마도 merge하는 과정에서 문제가 생긴 것 같습니다.  
수정바랍니다.

**Comment by herjn** [comment]
네 확인했습니다 ! 
좋은 지적 감사해요 😊

**Comment by high2092** [comment]
수정 후 PR 했습니다!

**Comment by rasauq1122** [comment]
수정 완료되었으니 issue 닫겠습니다!
